### ISSUE TITLE
出現在推文及文章圖片兩批各100~300張、文章標題、來源討論版和編號

### ISSUE THREAD

**Issue by bangyuwen** [neutral-info/neutral-info#17]
PTT
辛苦了，你可以先給我大概100~300張圖片和來源文章的討論版和編號麼？我想大致看一下會拿到的圖片種類和樣貌，還有出現在什麼樣的文章內。另外你爬取的資料是來自於推文或是PO文內應該是可以判斷的，我覺得文章內會出現的圖片和推文中出現的也會有些差別，而且文章中的圖片重要度高一點，可以的話也麻煩你幫我分開一下，最好有各一百張以上，不過方便給多少都好，就是要觀察一下資料樣貌和分佈，感恩。我現在正在試相似度分析，一邊找合適的資料集，把資料集格式轉一轉整合在一起訓練。我問過老闆假日我可以遠端借公司電腦來train，比家裡電腦快多了。

**Comment by kiko555** [comment]
目前已改由 @Chloeweidepei 接手，不過方向有點不同，所以我先關閉此issue
